/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as ApiSetupRouteImport } from './routes/api/setup'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminPppoeRouteImport } from './routes/admin/pppoe'
import { Route as AdminLocationsRouteImport } from './routes/admin/locations'
import { Route as ApiUploadLogoRouteImport } from './routes/api/upload/logo'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiSetupRoute = ApiSetupRouteImport.update({
  id: '/api/setup',
  path: '/api/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPppoeRoute = AdminPppoeRouteImport.update({
  id: '/pppoe',
  path: '/pppoe',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiUploadLogoRoute = ApiUploadLogoRouteImport.update({
  id: '/api/upload/logo',
  path: '/api/upload/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/setup': typeof SetupRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/pppoe': typeof AdminPppoeRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/setup': typeof ApiSetupRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/upload/logo': typeof ApiUploadLogoRoute
}
export interface FileRoutesByTo {
  '/setup': typeof SetupRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/pppoe': typeof AdminPppoeRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/setup': typeof ApiSetupRoute
  '/': typeof LayoutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/upload/logo': typeof ApiUploadLogoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/setup': typeof SetupRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/pppoe': typeof AdminPppoeRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/setup': typeof ApiSetupRoute
  '/_layout/': typeof LayoutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/upload/logo': typeof ApiUploadLogoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/'
    | '/setup'
    | '/admin/locations'
    | '/admin/pppoe'
    | '/admin/users'
    | '/api/setup'
    | '/admin/'
    | '/api/auth/$'
    | '/api/upload/logo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/admin/locations'
    | '/admin/pppoe'
    | '/admin/users'
    | '/api/setup'
    | '/'
    | '/admin'
    | '/api/auth/$'
    | '/api/upload/logo'
  id:
    | '__root__'
    | '/admin'
    | '/_layout'
    | '/setup'
    | '/admin/locations'
    | '/admin/pppoe'
    | '/admin/users'
    | '/api/setup'
    | '/_layout/'
    | '/admin/'
    | '/api/auth/$'
    | '/api/upload/logo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  SetupRoute: typeof SetupRoute
  ApiSetupRoute: typeof ApiSetupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUploadLogoRoute: typeof ApiUploadLogoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/setup': {
      id: '/api/setup'
      path: '/api/setup'
      fullPath: '/api/setup'
      preLoaderRoute: typeof ApiSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pppoe': {
      id: '/admin/pppoe'
      path: '/pppoe'
      fullPath: '/admin/pppoe'
      preLoaderRoute: typeof AdminPppoeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/upload/logo': {
      id: '/api/upload/logo'
      path: '/api/upload/logo'
      fullPath: '/api/upload/logo'
      preLoaderRoute: typeof ApiUploadLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminPppoeRoute: typeof AdminPppoeRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLocationsRoute: AdminLocationsRoute,
  AdminPppoeRoute: AdminPppoeRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  SetupRoute: SetupRoute,
  ApiSetupRoute: ApiSetupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUploadLogoRoute: ApiUploadLogoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
